name: jax-fem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - fenics-basix
  - orix
  - meshio
  - pyfiglet
  - petsc4py
  - pip
  - pip:
    - setuptools
    - wheel
    - gmsh
    - jax==0.4.14
    - jaxlib==0.4.14
