name: jax-fem
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy==1.24.4
  - scipy==1.11.1
  - pandas==2.0.3
  - matplotlib==3.7.2
  - fenics-basix==0.6.0
  - orix==0.11.1
  - gmsh==4.11.1
  - meshio==5.3.4
  - pyfiglet
  - petsc4py==3.19.4
  - pip==23.2.1
  # - git==2.41.0 only for dev
  - pip:
    # Utilities
    # - pytest only for dev
    - setuptools
    - wheel
    # - hypothesis only for dev
    # Minimal jax installation for GPU
    - jax==0.4.14
    - jaxlib==0.4.14
